# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/d-wazzle/Darwin-CV/OpenCV

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/d-wazzle/Darwin-CV/OpenCV

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/d-wazzle/Darwin-CV/OpenCV/CMakeFiles /home/d-wazzle/Darwin-CV/OpenCV/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/d-wazzle/Darwin-CV/OpenCV/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named openStream

# Build rule for target.
openStream: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 openStream
.PHONY : openStream

# fast build rule for target.
openStream/fast:
	$(MAKE) -f CMakeFiles/openStream.dir/build.make CMakeFiles/openStream.dir/build
.PHONY : openStream/fast

#=============================================================================
# Target rules for targets named faceDetectOP

# Build rule for target.
faceDetectOP: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 faceDetectOP
.PHONY : faceDetectOP

# fast build rule for target.
faceDetectOP/fast:
	$(MAKE) -f CMakeFiles/faceDetectOP.dir/build.make CMakeFiles/faceDetectOP.dir/build
.PHONY : faceDetectOP/fast

faceDetectOP.o: faceDetectOP.cpp.o

.PHONY : faceDetectOP.o

# target to build an object file
faceDetectOP.cpp.o:
	$(MAKE) -f CMakeFiles/faceDetectOP.dir/build.make CMakeFiles/faceDetectOP.dir/faceDetectOP.cpp.o
.PHONY : faceDetectOP.cpp.o

faceDetectOP.i: faceDetectOP.cpp.i

.PHONY : faceDetectOP.i

# target to preprocess a source file
faceDetectOP.cpp.i:
	$(MAKE) -f CMakeFiles/faceDetectOP.dir/build.make CMakeFiles/faceDetectOP.dir/faceDetectOP.cpp.i
.PHONY : faceDetectOP.cpp.i

faceDetectOP.s: faceDetectOP.cpp.s

.PHONY : faceDetectOP.s

# target to generate assembly for a file
faceDetectOP.cpp.s:
	$(MAKE) -f CMakeFiles/faceDetectOP.dir/build.make CMakeFiles/faceDetectOP.dir/faceDetectOP.cpp.s
.PHONY : faceDetectOP.cpp.s

openStream.o: openStream.cpp.o

.PHONY : openStream.o

# target to build an object file
openStream.cpp.o:
	$(MAKE) -f CMakeFiles/openStream.dir/build.make CMakeFiles/openStream.dir/openStream.cpp.o
.PHONY : openStream.cpp.o

openStream.i: openStream.cpp.i

.PHONY : openStream.i

# target to preprocess a source file
openStream.cpp.i:
	$(MAKE) -f CMakeFiles/openStream.dir/build.make CMakeFiles/openStream.dir/openStream.cpp.i
.PHONY : openStream.cpp.i

openStream.s: openStream.cpp.s

.PHONY : openStream.s

# target to generate assembly for a file
openStream.cpp.s:
	$(MAKE) -f CMakeFiles/openStream.dir/build.make CMakeFiles/openStream.dir/openStream.cpp.s
.PHONY : openStream.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... openStream"
	@echo "... faceDetectOP"
	@echo "... faceDetectOP.o"
	@echo "... faceDetectOP.i"
	@echo "... faceDetectOP.s"
	@echo "... openStream.o"
	@echo "... openStream.i"
	@echo "... openStream.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

